export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const VIEW_EMPLOYEE = 'VIEW_EMPLOYEE';
export const VIEW_EMPLOYEE_RES = 'VIEW_EMPLOYEE_RES';
export const GET_CREATE_EMPLOYEE_RESPONSE = 'GET_CREATE_EMPLOYEE_RESPONSE';
export const GET_EMPLOYEE_ID = 'GET_EMPLOYEE_ID';
export const GET_EMPLOYEE_ID_RES = 'GET_EMPLOYEE_ID_RES';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_EMPLOYEE_RES = 'GET_EMPLOYEE_RES';
export const CREATE_JOB = 'CREATE_JOB';

// export const CREATE_PROJECT = 'CREATE_PROJECT';
// export const GET_PROJECTS_RESPONSE = 'GET_PROJECTS_RESPONSE';
// export const GET_CREATE_PROJECTS_RESPONSE = 'GET_CREATE_PROJECTS_RESPONSE';
